name: Link Checker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check links in README
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --verbose --no-progress README.md
          fail: true
